security:
    encoders:
        PHPSanitizer\UserBundle\Entity\User:
            algorithm: bcrypt
    
    providers:
        php_sanitizer_user_provider:
            entity:
                class: PHPSanitizerUserBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            anonymous: ~
            provider: php_sanitizer_user_provider
            form_login:
                login_path: /
                check_path: /login_check
            logout:
                path: /logout
                target: /
    
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
